@echo off
setx DC_DB_REFSYS_USER "pDFa66yhH38YQ3KPRBY/Aw=="
setx DC_DB_REFSYS_USERIV "ZMox+rAlUovVLVLpnS4xAA=="
setx DC_DB_REFSYS_PASSWORD "NT1LHGdwbCgjeyow0qvxug=="
setx DC_DB_REFSYS_PASSWORDIV "PF4whNCBMtsZgP78CpEF5Q=="
setx DC_DB_REFSYS_SERVER "yqjaK0/F5sxdAtzPJpa2RQ=="
setx DC_DB_REFSYS_SERVERIV "pwabcP0fzguTWA2hca5RAA=="
setx DC_DB_REFSYS_DATABASE "LBPco7A/qYRGZDa67n4lDA=="
setx DC_DB_REFSYS_DATABASEIV "2H7ea+F3gFamEOi+XbpAEQ=="
setx DC_DB_REFSYS_KEY "A0spbGZY5Sfqiz+LLqqVJdZrBDkjBfHDG7MpirnFELo="

echo Success!
pause